### ISSUE TITLE
Handle larger screen resolutions

### ISSUE THREAD

**Issue by ferrreo** [legiblenews/community#12]
Hi,

Great service but legibility is greatly hindered on larger resolution displays. 

At 4k for example everything is crammed to the left and makes it exceptionally hard to read.

![image](https://user-images.githubusercontent.com/482133/176432542-5db3da71-eef1-40fa-9e94-cb2c39d7ba43.png)

Switching to margin auto for left and right margin combined with a larger width for max-w-prose with a media query for larger resolutions seems to be effective:

![image](https://user-images.githubusercontent.com/482133/176432927-ce2b4cb1-2a9a-4a67-828f-c81f0a1a0b45.png)

Is this something that could be looked into please?

Thanks

**Comment by bradgessler** [comment]
I could center it on wider screens and look into maybe making the text column slightly wider. I’m hesitant to do the latter because when text columns are too wide, it actually hurts readability.

I need to spend more time researching this, but a quick search while eating breakfast strawberries 🍓 turned up https://graphicdesign.stackexchange.com/questions/13724/recommended-column-width-for-text-reading-digital-vs-printed with a lot of good resources about optimal line width.

I’m hoping to avoid this, but at some point I wouldn’t be surprised if I have to make this a setting on the website.

**Comment by bradgessler** [comment]
One follow up question: do you browse the web in full screen as your screenshot shows? If not, could you take a screenshot of what the content looks like under your normal web browsing circumstances?

I have a 5K display and never browse in full screen, so I never run into the “large screen” problem.

Also what OS do you use? macOS users tend to be more comfortable having a bunch of smaller windows open on a screen at a given time, whereas windows users tend to have one window on screen maximized.

This info will help me better fine tune things, thanks!

**Comment by bradgessler** [comment]
Alrighty, I think this is reasonable. Here's before on a 5K display:

<img width="2672" alt="Screen Shot 2022-06-29 at 12 21 22" src="https://user-images.githubusercontent.com/4628/176518756-77e101d9-bd47-4588-af6a-a01fe73458df.png">

And after:

<img width="2672" alt="Screen Shot 2022-06-29 at 12 23 44" src="https://user-images.githubusercontent.com/4628/176519163-b074ba1c-784f-481f-9229-739da4b93182.png">

Changes I made:
* Content is centered on larger displays
* Text content is slightly wider on large displays

**Comment by ferrreo** [comment]
I browse fullscreen on linux, mac and windows at 4k. Changed look good, thanks for the quick fix!

**Comment by bradgessler** [comment]
Thanks for the feedback! I find myself liking the new look on a huge screen to 😎
