### ISSUE TITLE
Stripe subscription with Apple Pay

### ISSUE THREAD

**Issue by jmadkins** [legiblenews/community#13]
I wasn't sure the correct venue to raise this issue but I hope this is the correct place. 

I completed a 1 week trial of News Plus and was charged at the conclusion of the trial. However, when signed in with the same account it no longer appears that I have a valid subscription. 

The subscription should be under the email `justin@adkins.dev`.

![image](https://user-images.githubusercontent.com/7314701/177896118-73e6a151-3eaf-4979-a9fc-e40769d6e07f.png)

**Comment by bradgessler** [comment]
I'll check within the next few hours when I can access my laptop to login to the console and check it out. I'll update you on here.

**Comment by bradgessler** [comment]
K if you head to https://legiblenews.com/plus/subscription with your email it should say it expires about a year from now.

**Comment by jmadkins** [comment]
Yep, everything is showing up correctly on my end. Thank you!

**Comment by bradgessler** [comment]
I looked into this further and noticed that none of the subscribers in the past week had their Plus account properly credited because I didn't turn on the right web hooks in Stripe for production 🤦. 

Thanks so much for opening this issue so that I could catch that ahead of time.

For anybody else watching, I exported subscription payments from Stripe and properly credited the accounts. I also fixed the web hook issue so that future subscribers won't run into this issue.

Thanks @jmadkins! 🙏
