### ISSUE TITLE
Not receiving email

### ISSUE THREAD

**Issue by paustint** [legiblenews/community#16]
Not sure where else to ask for help, but I signed up for pro and setup daily email, but have yet to get anything to my inbox.

Can someone point me to a place where I can get support?

<img width="724" alt="image" src="https://user-images.githubusercontent.com/5461649/200977039-146ce198-15eb-4b60-87ce-caa98a3f837c.png">

**Comment by bradgessler** [comment]
Thanks for reaching out!

Turns out you found two bugs:

1. The emails aren't sending because I switched DNS providers, which broke DKIM. That means emails won't be delivered until I get that squared away. Amazon tells me that could be up to 72 hours before that gets squared away 😢 

    <img width="1100" alt="Screenshot 2022-11-11 at 08 27 43" src="https://user-images.githubusercontent.com/4628/201386061-99c79105-94e7-4f11-b6e5-20709e1d3893.png">

    In the meantime, you'll have to read The Weekly Edition at https://legiblenews.com/week after you sign in

2. I don't have an obvious support email address or web page, which is hugely problematic. I'm going to add that to the `/plus` page and a separate `/support` page with the correct contact information.

I'll keep updating this thread as I fix these issues.

**Comment by paustint** [comment]
I got an email today!

**Comment by bradgessler** [comment]
Emails should be working again! DKIM configurations are verified and I have cron running at 0:15 UTC to deliver emails.

Next up: I need to add a plus support page.

**Comment by bradgessler** [comment]
I can verify I'm also receiving weekly and daily emails.

**Comment by bradgessler** [comment]
For support, I added an email link at https://legiblenews.com/plus/subscription under "Give feedback, request features, and get help" that opens an email client with `support@legiblenews.com` and some pre-populated support information.

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/4628/203182299-4a22c78a-7943-414b-9f0d-fbc3a7f6d4ef.png">

**Comment by bradgessler** [comment]
Closing out this issue. If there's more problems feel free to comment here or open a new issue.

Thanks!
