### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by dezren39** [legiblenews/community#4]
Can you add a favicon so that my chrome bookmarks bar looks nice
![image](https://user-images.githubusercontent.com/11225574/149015056-dd305685-a4ea-4911-a876-f0b56e6403f6.png)

**Comment by bradgessler** [comment]
Good idea! I made it blank to minimize requests, but what you're saying makes way more sense. I'll whip something up.

Thanks so much for your feedback 

🙏

**Comment by bradgessler** [comment]
<img width="1008" alt="Screen Shot 2022-02-01 at 13 40 35" src="https://user-images.githubusercontent.com/4628/152055987-06e0c425-994d-4cb3-bb4d-0c1abffa171f.png">

I considered two icons and chose "News" because it's more legible at that font size and more sensible than "LN" (what does that mean?)

Caching is always kind of weird for favicons, but this should pickup the new icon. You might have to try adding it to your bookmarks again to pick it up.

Closing this issue for now. If there's problems please comment below and I'll re-open.
